Repository nhs-england-tools/playwright-python-blueprint, pull requests merged in 2024-11, with the labels that each got.

#25 Axe utility class
  .editorconfig
  .github/actions/check-axe-version/action.yaml
  .github/workflows/axe-dependency-check.yaml
  .github/workflows/stage-3-build.yaml
  .gitignore
  .gitleaks.toml
  .gitleaksignore
  README.md
  docs/adr/ADR-001_Use_git_hook_and_GitHub_action_to_check_the_editorconfig_compliance.md
  docs/adr/ADR-002_Scan_repository_for_hardcoded_secrets.md
  docs/adr/ADR-003_Acceptable_use_of_GitHub_PAT_and_Apps_for_authN_and_authZ.md
  docs/adr/ADR-XXX_Agree_CICD_pipeline_structure.md
  docs/adr/ADR-nnn_Any_Decision_Record_Template.md
  docs/adr/assets/ADR-003/examples/bash/README.md
  docs/adr/assets/ADR-003/examples/bash/script.sh
  docs/adr/assets/ADR-003/examples/nodejs/.gitignore
  docs/adr/assets/ADR-003/examples/nodejs/README.md
  docs/adr/assets/ADR-003/examples/nodejs/main.ts
  docs/adr/assets/ADR-003/examples/nodejs/package.json
  docs/adr/assets/ADR-003/examples/nodejs/tsconfig.json
  docs/adr/assets/ADR-003/examples/python/README.md
  docs/adr/assets/ADR-003/examples/python/main.py
  docs/adr/assets/ADR-003/examples/python/requirements.txt
  docs/developer-guides/Bash_and_Make.md
  docs/developer-guides/Scripting_Docker.md
  docs/developer-guides/assets/make_help.png
  docs/diagrams/.gitignore
  docs/diagrams/CD_Pipeline_Structure.drawio
  docs/diagrams/CD_Pipeline_Structure.png
  docs/diagrams/Repository_Template.drawio
  docs/diagrams/Repository_Template_GitHub_Generic.png
  docs/user-guides/Perform_static_analysis.md
  docs/user-guides/Run_Git_hooks_on_commit.md
  docs/user-guides/Scan_dependencies.md
  docs/user-guides/Scan_secrets.md
  docs/user-guides/Sign_Git_commits.md
  docs/user-guides/Test_GitHub_Actions_locally.md
  docs/utility-guides/Axe.md
  pytest.ini
  tests_utils/README.md
  tests_utils/__init__.py
  tests_utils/test_axe.py
  utils/__init__.py
  utils/axe.py
  utils/resources/axe.js
Labels: enhancement, functionality

#27 Axe Workflow Fix
  .github/workflows/axe-dependency-check.yaml
  .gitleaksignore
  utils/resources/README.md
Labels: bug, github_actions

#29 Custom filename support for Axe reporting
  docs/utility-guides/Axe.md
  tests/__init__.py
  tests_utils/test_axe.py
  utils/axe.py
Labels: documentation, enhancement

#31 WCAG 2.2 Implementation in Axe Util
  docs/utility-guides/Axe.md
  tests/test_example.py
  utils/axe.py
Labels: bug

#32 Add functionality to execute Axe against multiple URLs
  README.md
  docs/utility-guides/Axe.md
  utils/axe.py
Labels: enhancement, functionality

#33 Added date_time utility, unit tests, and utility guide.
  docs/utility-guides/DateTimeUtility.md
  tests_utils/test_date_time_utils.py
  utils/date_time_utils.py
Labels: enhancement, functionality

#34 Getting Started Guides
  .vscode/extensions.json
  .vscode/settings.json
  Makefile
  docs/getting-started/1_Understanding_Playwright_Python.md
  docs/getting-started/2_Blueprint_File_Breakdown.md
  docs/getting-started/img/1-codegen.png
  docs/getting-started/img/2-codegen_tools.png
  docs/getting-started/img/3-show_trace.png
  infrastructure/environments/dev/.gitkeep
  pages/.gitkeep
  pages/__init__.py
  pytest.ini
  tests_utils/test_axe.py
  tests_utils/test_date_time_utils.py
Labels: documentation

#36 User Tools Utility
  .vscode/settings.json
  README.md
  docs/getting-started/2_Blueprint_File_Breakdown.md
  docs/utility-guides/NHSNumberTools.md
  docs/utility-guides/UserTools.md
  tests_utils/resources/test_users.json
  tests_utils/test_nhs_number_tools.py
  tests_utils/test_user_tools.py
  users.json
  utils/axe.py
  utils/date_time_utils.py
  utils/nhs_number_tools.py
  utils/user_tools.py
Labels: enhancement, functionality, structure

#37 Adding pythonpath variable
  .vscode/settings.json
  docs/getting-started/2_Blueprint_File_Breakdown.md
  pytest.ini
Labels: configuration, python
